[package]
name = "compute_provider"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0", default-features = false, features = ['std'] }
compute-provider-core ={ path = "../../core"}