[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "../evm_base"]
test = "tests"
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
via_ir = true
optimizer = true
optimizer-runs = 10_000_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
