[package]
name = "compute-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
fhe = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
serde = { version = "1.0", features = ["derive", "std"] }
zk-kit-imt = "0.0.5"
sha3 = "0.10.8"
num-bigint = "0.4"
num-traits = "0.2"
hex = "0.4"
light-poseidon = "0.2.0"
ark-ff = "0.4.2"
ark-bn254 = "0.4.0"
rand = "0.8"
rayon = "1.10.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
