[workspace]
resolver = "2"
members = ["host", "methods", "core"]


[workspace.dependencies]
risc0-build = { version = "1.0.5" }
risc0-build-ethereum = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.0.0" }
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.0.0" }
risc0-zkvm = { version = "1.0.5", default-features = false, features = ["std", "client"] }
risc0-zkp = { version = "1.0.5" }
fhe = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
serde = { version = "1.0", features = ["derive", "std"] }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
