[package]
name = "compute-provider-host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { workspace = true }
risc0-build-ethereum = { workspace = true }
risc0-ethereum-contracts = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
compute-provider-core ={ path = "../core"}
fhe = { workspace = true }
fhe-traits = { workspace = true }
rand = "0.8"

