[package]
name = "rfv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
console = "0.15.7"
fhe = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
fhe-util = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
rand_chacha = "0.3.1"
rand = "0.8.5"
ethers = "2.0"
compute-provider-host = { path = "../compute_provider/host" }
getrandom = { version = "0.2.11", features = ["js"] }
# Ethers' async features rely upon the Tokio async runtime.
tokio = { version = "1.37.0", features = ["full"] }
bincode = "1.0"
hyper = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
hyper-tls = "0.6.0"
iron = "0.6.0"
router = "0.6.0"
walkdir = "2.5.0"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
wasm-bindgen = "0.2"
chrono = "0.4.38"
sled = "0.34"
once_cell = "1.19.0"
async-std = { version = "1", features = ["attributes", "tokio1"] }
bytes = "1.6.0"
iron-cors = "0.8.0"
headers = "0.4.0"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
