[env]
INFURA_KEY = "INFURA_KEY" # Your Infura key
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Anvil's private key
RPC_URL = "http://0.0.0.0:8545" # Local RPC
CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3" # Enclave Address